Align assembly XSD version with plugin used
apache/maven pull request #728
Opened 2022-04-27 09:04 UTC by cstamas

As title says, XSD is ancient old 2.0.0, while all
latest assembly plugins uses 2.1.0.

Not that this matters or changes anything at all,
this is more about correctness.

2022-04-27 09:34 UTC, michael-o requested changes
Still has `http://maven.apache.org/ASSEMBLY/2.0.0`

2022-04-27 09:48 UTC, cstamas commented
> Still has `http://maven.apache.org/ASSEMBLY/2.0.0`

Fixed the missed ones.

2022-04-27 09:53 UTC, michael-o approved these changes

2022-04-27 10:25 UTC, slachiewicz approved these changes

2022-04-27 13:14 UTC, merged

2025-07-07 08:13 UTC, jira-importer commented
Resolve #9132