[3.9.x] [MNG-7473] Backport Maven BOM to 3.9.0
apache/maven pull request #859
Opened 2022-10-28 18:00 UTC by cstamas

---

https://issues.apache.org/jira/browse/MNG-7473

2022-10-29 07:01 UTC, gnodet commented on maven-bom/pom.xml
> +         - maven-compat, only used by apache-maven distributions to support older releases
I'm not sure it makes sense to not include `maven-compat`.  This is still required at runtime to run maven, so any plugin integration test will require it afaik.

2022-10-29 07:05 UTC, gnodet commented on maven-bom/pom.xml
> +         - apache-maven, as it delivers the binaries
Can't the distribution be used for ITs ?
  https://github.com/apache/maven-build-cache-extension/blob/master/pom.xml#L401-L409
Unfortunately, I don't think the `m-dependency-p` can leverage the info from the BOM, but I wonder if there are other use cases ?

2022-10-29 07:05 UTC, gnodet requested changes
Not sure about leaving out `apache-maven` and `maven-compat`...

2022-10-29 07:11 UTC, gnodet approved these changes
This is in line with current master, so out of topic for this PR.

2022-10-29 08:21 UTC, slawekjaranowski approved these changes

2022-10-29 10:21 UTC, kwin commented
What about the comments from https://issues.apache.org/jira/browse/MNG-6806?focusedCommentId=17532971&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17532971.
This BOM is not really useful for plugin developers in its current form as putting the right version for those artifacts is a no-brainer. Can we have one which manages all artifacts exposed by the Core Classloader from the Maven distribution?

2022-10-29 10:39 UTC, cstamas commented
@gnodet I also think leaving out maven-compat makes no sense (at least for 3.x line)
@kwin I completely agree, but was down voted for doing that by arguments "it is not BOM"...

In essence, I wanted to backport what master/4.x has, would merely add maven-compat and later we can see for the rest...

2022-10-29 10:43 UTC, kwin commented
Maybe we can add another artifact then and call it maven-core-classloader-dep-mgmt. I don’t care about naming here, I primarily care about better support for plugin developers.

2022-10-29 18:50 UTC, michael-o approved these changes

2022-11-26 19:41 UTC, cstamas commented
Am somewhat aligned with @kwin here, and am now on the other side: backporting the BOM from master to 3.9.x (as is) does not makes much sense (plus as said above, where is compat, where is maven etc), so am rather to close this out w/o merge. Will give 24h for anyone interested to respond (or just +1) this comment as sign for "I agree: close out this PR w/o merge".

2022-12-01 12:30 UTC, cstamas commented
Am backing out from backporting BOM, it makes no sense as is IMHO

2022-12-01 12:30 UTC, closed without merging

2025-07-07 08:13 UTC, jira-importer commented
Resolve #9128