[MNG-7600] LocalRepositoryManager is created to early
apache/maven pull request #876
Opened 2022-11-18 20:27 UTC by slawekjaranowski

LocalRepositoryManager needs configurations from RepositorySystemSession so must be created after session configuration is finished.

---

Following this checklist to help us incorporate your
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] SUMMARY`, where you replace `MNG-XXX`
       and `SUMMARY` with the appropriate JIRA issue. Best practice is to use the JIRA issue
       title in the pull request title and in the first line of the commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

2022-11-20 19:51 UTC, michael-o requested changes
to => too

2022-11-20 21:43 UTC, michael-o requested changes
The JIRA issue says that properties which are user one are required. MAybe an IT or an example can better desribe the need for?

2022-11-20 21:43 UTC, michael-o commented on maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
> +        setupLocalRepositoryManager( request, session );
`setUp`. Noun "setup", verb "to set up"

2022-11-21 06:48 UTC, slawekjaranowski commented on maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
> +        setupLocalRepositoryManager( request, session );
method renamed

2022-11-21 06:53 UTC, slawekjaranowski commented
> The JIRA issue says that properties which are user one are required. MAybe an IT or an example can better desribe the need for?

I know - it will be appreciated to have it tests for such cases ... 

But the problem is that currently it is difficult to mix different Local Manager configurations between parent Maven process which execute tests and Maven process under test. 

Last discussion on the slack ...

2022-11-21 08:34 UTC, michael-o approved these changes
So this basically changes position to have a chance to access all properties...

Does this qualify for 3.9.0?

2022-11-21 08:54 UTC, slawekjaranowski commented
> So this basically changes position to have a chance to access all properties...

exactly

> Does this qualify for 3.9.0?

yes, as mentioned in issue

2022-11-21 15:45 UTC, merged

2025-07-07 08:03 UTC, jira-importer commented
Resolve #8852